id: PF154214E
initial_creation_type: input
source_metadata:
  title: Shabkar Tsokdruk Rangdrol Series
  language: de
  description: 'Texts by the great poet and Dzogchen adept Shabkar Tsokdruk Rangdrol
    (zhabs dkar tshogs drug rang grol, 1781–1851):'
  volume:
    a740db5f77654be0b79ebc404b10512c:
      title: Concise Preliminaries Practice
      parent: Preliminary Practice
    c0ce11ad396146fd92ef3f49f7cea1d2:
      title: A Short Song of Practice
      parent: Songs
    e57aa87c781245ecae0a33ed31fca018:
      title: A Song of Compassion
      parent: Songs
    ca2452ad9534449ea24dbc25b590ab60:
      title: When Remembering My Mother
      parent: Songs
    24ccc096c10b46c5ada79824d7c53266:
      title: Light Offering Aspiration Prayer
      parent: Light Offering Prayer
created_at: '2022-03-01T01:31:13.408028'
last_modified_at: '2022-03-01T01:31:13.408031'
